SELECT
  kcu.TABLE_SCHEMA AS fk_database,
  kcu.TABLE_NAME AS fk_table,
  kcu.COLUMN_NAME AS fk_column,
  kcu.REFERENCED_TABLE_SCHEMA AS pk_database,
  kcu.REFERENCED_TABLE_NAME AS pk_table,
  kcu.REFERENCED_COLUMN_NAME AS pk_column,
  rc.CONSTRAINT_NAME AS fk_constraint_name
FROM
  INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
JOIN
  INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
  ON rc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
  AND rc.CONSTRAINT_SCHEMA = kcu.CONSTRAINT_SCHEMA
WHERE
  rc.CONSTRAINT_SCHEMA = 'Rfam';
